"""
Metrics 模块入口


"""

from src.config.constants import CLASSICAL_PATTERNS, PROPP_FUNCTIONS

from .aggregate import (
    AggregateResult,
    aggregate_all_metrics,
)
from .character_metrics import (
    GREIMAS_FUNCTIONS,
    compute_antagonist_strength_gap,
    compute_average_clustering,
    compute_character_closeness_centrality,
    compute_character_degree_centrality,
    compute_character_eigenvector_centrality,
    compute_character_function_coverage,
    compute_clustering_coefficient,
    compute_greimas_coverage,
    compute_largest_component_size,
    compute_number_of_connected_components,
    compute_protagonist_betweenness,
    compute_relation_change_frequency,
    compute_relation_network_density,
)
from .emotion_metrics import lexical_sentiment_density, pos_neg_ratio
from .emotion_metrics_extra import (
    compute_arc_delta,
    compute_emotion_polarity_distribution,
    compute_emotion_recovery_speed,
    compute_lexical_emotion_trend,
    compute_pivot_moment_density,
    compute_pos_neg_ratio,
)
from .lexicon_metrics import count_mixed_hits, term_mixed_counts
from .narrative_metrics import (
    ThreeActBoundaryCandidate,
    ThreeActStructureDiagnostics,
    analyze_three_act_structure,
    compute_cliffhanger_rate,
    compute_climax_profile,
    compute_climax_spacing,
    compute_event_density,
    compute_middle_collapse_index,
    compute_three_act_ratio_v2,
    find_global_peak,
    find_local_peaks,
    find_valley_before_peak,
)
from .rhythm_metrics import tension_composite, tension_proxy
from .style_metrics import (
    average_word_length,
    dialogue_ratio,
    function_word_distribution,
    lexicon_density,
    metaphor_density,
    mtld,
    pause_density,
    semantic_category_density,
    sensory_density,
    sentence_length_stats,
    ttr,
    word_frequency_breadth,
)
from .style_metrics_extra import (
    CLASSICAL_IMAGERY,
    FUNCTION_WORDS,
    SEMANTIC_CATEGORY_KEYS,
    compute_avg_word_len,
    compute_category_density,
    compute_classical_sentence_ratio,
    compute_function_word_vector,
    compute_idiom_density,
    compute_imagery_density,
    compute_sent_len_std,
    compute_vocab_breadth,
)
from .text_utils import dialogue_length, split_sentences, tokenize_words
from .timeline_metrics import (
    LifecycleEventDTO,
    NarrativePhase,
    PlotFlagsDTO,
    RelationEventDTO,
    TimelineCompositeNodeDTO,
    TimelineNodeDTO,
    calculate_tension_percentile,
    compose_composite_timeline_nodes,
    compute_four_phases,
    compute_importance_score,
    convert_to_timeline_phases,
    serialize_timeline_composite_node,
    serialize_timeline_node,
    serialize_timeline_phases,
)

__all__ = [
    "AggregateResult",
    "aggregate_all_metrics",
    "LifecycleEventDTO",
    "NarrativePhase",
    "PlotFlagsDTO",
    "RelationEventDTO",
    "TimelineCompositeNodeDTO",
    "TimelineNodeDTO",
    "calculate_tension_percentile",
    "compose_composite_timeline_nodes",
    "compute_four_phases",
    "compute_importance_score",
    "convert_to_timeline_phases",
    "serialize_timeline_composite_node",
    "serialize_timeline_node",
    "serialize_timeline_phases",
    "CLASSICAL_IMAGERY",
    "CLASSICAL_PATTERNS",
    "FUNCTION_WORDS",
    "PROPP_FUNCTIONS",
    "GREIMAS_FUNCTIONS",
    "SEMANTIC_CATEGORY_KEYS",
    "compute_antagonist_strength_gap",
    "compute_average_clustering",
    "compute_arc_delta",
    "compute_avg_word_len",
    "compute_category_density",
    "compute_character_closeness_centrality",
    "compute_character_degree_centrality",
    "compute_character_eigenvector_centrality",
    "compute_character_function_coverage",
    "compute_classical_sentence_ratio",
    "compute_cliffhanger_rate",
    "compute_climax_profile",
    "compute_climax_spacing",
    "compute_clustering_coefficient",
    "compute_emotion_polarity_distribution",
    "compute_emotion_recovery_speed",
    "compute_event_density",
    "compute_function_word_vector",
    "compute_greimas_coverage",
    "compute_lexical_emotion_trend",
    "compute_idiom_density",
    "compute_imagery_density",
    "compute_largest_component_size",
    "compute_middle_collapse_index",
    "compute_number_of_connected_components",
    "compute_pivot_moment_density",
    "compute_pos_neg_ratio",
    "compute_protagonist_betweenness",
    "compute_relation_change_frequency",
    "compute_relation_network_density",
    "compute_sent_len_std",
    "compute_three_act_ratio_v2",
    "compute_vocab_breadth",
    "count_mixed_hits",
    "term_mixed_counts",
    "ThreeActBoundaryCandidate",
    "ThreeActStructureDiagnostics",
    "analyze_three_act_structure",
    "average_word_length",
    "dialogue_length",
    "dialogue_ratio",
    "find_global_peak",
    "find_local_peaks",
    "find_valley_before_peak",
    "function_word_distribution",
    "lexical_sentiment_density",
    "lexicon_density",
    "metaphor_density",
    "mtld",
    "pause_density",
    "pos_neg_ratio",
    "sentence_length_stats",
    "semantic_category_density",
    "sensory_density",
    "split_sentences",
    "tension_composite",
    "tension_proxy",
    "tokenize_words",
    "ttr",
    "word_frequency_breadth",
]
